# restrict branches in order to prevent spam from feature branches
branches:
  only:
    - develop
    - master

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --no-interaction

script:
  - phpunit

sudo: false
